yandex_partner_id = 136856;
                    yandex_site_bg_color = 'FFFFFF';
                    yandex_stat_id = 10;
                    yandex_ad_format = 'direct';
                    yandex_font_size = 1.2;
                    yandex_direct_type = 'flat';
                    yandex_direct_limit = 4;
                    yandex_direct_title_font_size = 3;
                    yandex_font_family = 'courier new';
                    yandex_direct_title_color = 'FF0000';
                    yandex_direct_url_color = '000000';
                    yandex_direct_text_color = '333333';
                    yandex_direct_hover_color = '0FACEA';
                    yandex_direct_favicon = true;
                    yandex_no_sitelinks = true;
                    document.write('<scr'+'ipt type="text/javascript" src="//an.yandex.ru/system/context.js"></scr'+'ipt>');