<?php //require_once("../../../wp-config.php"); ?>


<div id="mainMenu">


    
      <div class="imgMenu">
         <img  src="<?php bloginfo('template_directory'); ?>/images/icons/centralnoe-otoplenie.jpg" alt="Центральное отопление" />   
     </div>
     <div class="urlMenu">
          <a class="mainLink" title="Центральное отопление" href="/category/centralnoe-otoplenie">Центральное отопление</a>
            <ul class="centerMenu">
                 <li class="inCenterMenu"><a href="/category/centralnoe-otoplenie/vodyanoe-otoplenie" title="Водяное отопление" >Водяное</a></li>
                 <li class="inCenterMenu"><a href="/category/centralnoe-otoplenie/parovoe-otoplenie" title="Паровое отопление" >Паровое</a></li>
                 <li class="inCenterMenu"><a href="/category/centralnoe-otoplenie/vozdushnoe-otoplenie" title="Воздушное отопление" >Воздушное</a></li>
                 <li class="inCenterMenu"><a href="/category/centralnoe-otoplenie/kombinirovannoe-otoplenie" title="Комбинированное отопление" >Комбинированное</a></li>
            </ul>
    </div>
    
    <div class="clear"></div>
     <div class="imgMenu">
         <img  src="<?php bloginfo('template_directory'); ?>/images/icons/mestnoe-otoplenie.jpg" alt="Местное отопление" />   
     </div>
    <div class="urlMenu">
          <a class="mainLink" title="Местное отопление" href="/category/mestnoe-otoplenie">Местное отопление</a> 
    <ul class="centerMenu">
        
                <li class="inCenterMenu"><a href="/category/mestnoe-otoplenie/gazovoe-otoplenie" title="Газовое отопление" >Газовое</a></li>
                <li class="inCenterMenu"><a href="/category/mestnoe-otoplenie/elektricheskoe-otoplenie" title="Электрическое отопление" >Электрическое</a></li>
                <li class="inCenterMenu"><a href="/category/mestnoe-otoplenie/pechnoe-otoplenie" title="Печное отопление" >Печное</a></li>
                <li class="inCenterMenu"><a href="/category/mestnoe-otoplenie/avtonomnoe-otoplenie" title="Автономное отопление" >Автономное</a></li>
                
            </ul>
     </div>       
    
  <div class="clear"></div>
  
  
  
         <div class="imgMenu">
         <img  src="<?php bloginfo('template_directory'); ?>/images/icons/alternativnoe-otoplenie.jpg" alt="Альтернативное отопление" />   
     </div>
      <div class="urlMenu">
          <a class="mainLink" title="Альтернативное отопление" href="/category/alternativnoe-otoplenie">Альтернативное отопление</a>   
    <ul class="centerMenu">
                <li class="inCenterMenu m5li"><a href="/category/alternativnoe-otoplenie/geotermalnoe-otoplenie" title="Геотермальное отопление (энергия земли)" >Геотермальное</a></li>
                <li class="inCenterMenu m5li"><a href="/category/alternativnoe-otoplenie/geliosistemy" title="Гелиосистемы отопления (Солнечная энергия)" >Гелиосистемы</a></li>
                <li class="inCenterMenu m5li"><a href="/category/alternativnoe-otoplenie/infrakrasnoe-otoplenie" title="Инфракрасное отопление" >Инфракрасное</a></li>
                <li class="inCenterMenu m5li"><a href="/category/alternativnoe-otoplenie/otoplenie-vodorodom" title="Водородное отопление" >Водородное</a></li>
                <li class="inCenterMenu m5li"><a href="/category/alternativnoe-otoplenie/indukcionnoe-otoplenie" title="Индукционное отопление" >Индукционное</a></li>
            </ul>
     </div>
     
     
           <div class="clear"></div>

          <div class="distMenu"></div> 
     <div class="imgMenu">
         <img  src="<?php bloginfo('template_directory'); ?>/images/icons/obsluzivanie.jpg" alt="Обслуживание" />   
     </div>
         <div class="urlMenu">
          <a class="mainLink" title="Обслуживание систем отопления" href="/category/obsluzhivanie-sistem-otopleniya">Обслуживание систем отопления</a>    
    <ul class="centerMenu">
                <li class="inCenterMenu"><a href="/category/obsluzhivanie-sistem-otopleniya/montaz" title="Монтаж" >Монтаж</a></li>
                <li class="inCenterMenu"><a href="/category/obsluzhivanie-sistem-otopleniya/remont" title="Обслуживание и ремонт" >Ремонт</a></li>
                <li class="inCenterMenu"><a href="/category/obsluzhivanie-sistem-otopleniya/proektirovanie-i-raschet" title="Проектирование и расчет, виды и схемы отопления" >Проектирование и расчет</a></li>
               

                
            </ul>
     </div>
     
            <div class="clear"></div>
            
                 <div class="imgMenu">
         <img  src="<?php bloginfo('template_directory'); ?>/images/icons/otaplivaemie-obekty.jpg" alt="Отапливаемые объекты" />   
     </div>
         <div class="urlMenu">
          <a class="mainLink" title="Отапливаемые объекты" href="/category/otaplivaemye-obekty">Отапливаемые объекты</a>    
    <ul class="centerMenu">
                <li class="inCenterMenu"><a href="/category/otaplivaemye-obekty/chastnyj-dom" title="Частный и дачный дома" >Дом</a></li>
                <li class="inCenterMenu"><a href="/category/otaplivaemye-obekty/kvartira" title="Квартира" >Квартира</a></li>
                <li class="inCenterMenu"><a href="/category/otaplivaemye-obekty/teplica" title="Теплица" >Теплица</a></li>
                <li class="inCenterMenu"><a href="/category/otaplivaemye-obekty/banya" title="Баня" >Баня</a></li>
                <li class="inCenterMenu"><a href="/category/otaplivaemye-obekty/garazh" title="Гараж" >Гараж</a></li>
                <li class="inCenterMenu"><a href="/category/otaplivaemye-obekty/promyshlennye-pomeshheniya" title="Промышленные помещения" >Промышленные</a></li>
                
            </ul>
     </div>        
     <div class="clear"></div>
            
            
            
            
          <div class="distMenu"></div> 
     <div class="imgMenu">
         <img  src="<?php bloginfo('template_directory'); ?>/images/icons/nasosy.jpg" alt="Комплектующие и расходные материалы" />   
     </div>
         <div class="urlMenu">
          <a class="mainLink" title="Комплектующие и расходные материалы" href="/category/komplektuyushhie">Комплектующие и расходные материалы</a>    
    <ul class="centerMenu">
                <li class="inCenterMenuB"><a href="/category/radiatory-otopleniya" title="Радиаторы отопления" >Радиаторы</a>
                  <ul class="inCenterMenuUl">
                    <li><a href="/category/radiatory-otopleniya/alyuminievye-radiatory" title="Алюминиевые радиаторы" >Алюминиевые</a></li>
                    <li><a href="/category/radiatory-otopleniya/bimetallicheskie-radiatory" title="Биметаллические радиаторы" >Биметаллические</a></li>
                    <li><a href="/category/radiatory-otopleniya/chugunnye-radiatory" title="Чугунные радиаторы" >Чугунные</a></li>
                    <li><a href="/category/radiatory-otopleniya/stalnye-radiatory" title="Стальные радиаторы" >Стальные</a></li>
                    <li><a href="/category/radiatory-otopleniya/vodyanye-radiatory" title="Водяные радиаторы" >Водяные</a></li>
                    <li><a href="/category/radiatory-otopleniya/elektricheskie-radiatory" title="Электрические" >Электрические</a></li>
                    <li><a href="/category/radiatory-otopleniya/gazovye-konvektory" title="Газовые конвекторы" >Газовые</a></li>
                    <li><a href="/category/radiatory-otopleniya/konvektory" title="Конвекторы" >Конвекторы</a></li>
                    <li><a href="/category/radiatory-otopleniya/ekrany-dlya-batarej-otopleniya" title="Экраны для батарей отопления" >Экраны</a></li>
                  </ul>
                
                </li>
                
                <li class="inCenterMenuB"><a href="/category/kotly" title="Котлы отопления" >Котлы</a>
                  <ul class="inCenterMenuUl">
                      <li><a href="/category/kotly/gazovye-kotly" title="Газовые котлы" >Газовые</a></li>
                      <li><a href="/category/kotly/tverdotoplivnye-kotly" title="Твердотопливные котлы" >Твердотопливные</a></li>                
                      <li><a href="/category/kotly/elektricheskie-kotly" title="Электрические котлы" >Электрические</a></li> 
                      <li><a href="/category/kotly/zhidkotoplivnye-kotly" title="Жидкотопливные котлы" >Жидкотопливные</a></li>    
                      <li><a href="/category/kotly/alternativnye-kotly" title="Альтернативные котлы" >Альтернативные</a></li>
                  </ul>
                
                </li>
                
                
                <li class="inCenterMenuB"><a href="/category/truby" title="Трубы для отопления" >Трубы</a>
                   <ul class="inCenterMenuUl">
                     <li><a href="/category/truby/polipropilenovye-truby" title="Полипропиленовые трубы" >Полипропиленовые</a></li>
                     <li><a href="/category/truby/metalloplastikovye-truby" title="Металлопластиковые трубы" >Металлопластиковые</a></li>
                     <li><a href="/category/truby/ocinkovannye-truby" title="Оцинкованные трубы" >Оцинкованные</a></li>
                     <li><a href="/category/truby/plastikovye-truby" title="Пластиковые трубы" >Пластиковые</a></li>
                     <li><a href="/category/truby/stalnye-truby" title="Стальные трубы" >Стальные</a></li>
                     <li><a href="/category/truby/sshityj-polietilen" title="Сшитый полиэтилен" >Сшитый полиэтилен</a></li>
                     <li><a href="/category/truby/mednye-truby" title="Медные трубы" >Медные</a></li>
                   </ul>
                </li>
                <li class="inCenterMenuB"><a href="/category/nasosy" title="Насосы" >Насосы</a>
                   <ul class="inCenterMenuUl">
                     <li><a href="/category/nasosy/cirkulyacionnye-nasosy" title="Циркуляционные насосы" >Циркуляционные</a></li>
                     <li><a href="/category/nasosy/teplovye-nasosy" title="Тепловые насосы" >Тепловые</a></li>
                  </ul>   
                </li>
                
                

                
            </ul>
     </div>
       
      
                  
     <div class="clear"></div>

     

 </div>

 <div id="LastPostsBox">
        <!--noindex--><p class="LastPub">Последние публикации</p><!--/noindex-->
          <ul class="ulLastPosts">
        <?php wp_get_archives("type=postbypost&limit=8"); ?> 
        
                        
        
        </ul>
        </div>

<div class="social">
                <div class="social">
                    <div
                    class="yashare-auto-init"
                    data-yashareLink=""
                    data-yashareL10n="ru"
                    data-yashareType="big"
                    data-yashareQuickServices="vkontakte,facebook,twitter,moimir"
                    data-yashareTheme="counter"
                    ></div>    
            </div> 
</div> 
 <div class="vkcom">
       

        <!-- VK Widget -->
        <div id="vk_groups"></div>
        <script type="text/javascript">
        VK.Widgets.Group("vk_groups", {mode: 0, width: "300", height: "320", color1: 'FFFFFF', color2: '2B587A', color3: '5B7FA6'}, 76403901);
        </script>
       
       </div>       
<div class="clear"></div>
    <div class="mostViewed">
    
      <?php get_most_viewed('post', 15); ?>
   
   </div>
<div class="clear"></div>



